package `2024_planned`.hashTables

/**
 * You are given two strings s and t.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Return the letter that was added to t.
 */
class FindTheDifference {
    // time O(n) / space O(1)
    fun findTheDifference(s: String, t: String): Char {
        var result = 0

        s.forEach { result = result xor it.toInt() }
        t.forEach { result = result xor it.toInt() }

        return result.toChar()
    }

    // time / space O(n)
    fun findTheDifference2(s: String, t: String): Char {
        val lettersInS = mutableMapOf<Char, Int>()
        s.forEach {
            lettersInS[it] = lettersInS.getOrDefault(it, 0) + 1
        }

        val lettersInT = mutableMapOf<Char, Int>()
        t.forEach {
            lettersInT[it] = lettersInT.getOrDefault(it, 0) + 1
        }

        lettersInT.forEach { (key, value) ->
            if (!lettersInS.containsKey(key) || lettersInS.getOrDefault(key, 0) < value) {
                return key
            }
        }

        return ' '
    }
}